### ISSUE TITLE
Allow for manual setting of delimiters

### ISSUE THREAD

**Issue by bittelc** [jreut/hl7#8]
Some of our test suite does, and will continue to, rely on "micro-data", meaning that is incomplete data in terms of an entire HL7 message (which requires an MSH segment header) but that still abides by the same HL7 protocol.
Example: `foo^bar`

Without the MSH segment header, this micro-data has no context to inform whether the `^` is a segment, component, etc. delimiter.

In order to test this micro-data, along with greater potential for future use, it is necessary that we allow for the manual setting of a message's delimiters. Given the above example, we could manually set the delimiters such that our parser knows that the `^` character is a component delimiter.

**Comment by jreut** [comment]
I think we already [do this](https://github.com/jreut/hl7/blob/master/lib/hl7/parser.rb#L7-L14) in a slightly different way.
